export const LOCATIONS = [
    {
        id: 'chennai',
        city: 'Chennai',
        type: 'Headquarters',
        address: 'Tidel Park, Taramani, Chennai 600113',
        phone: '+91 44 0000 0000',
        email: 'chennai@opmw.in',
        isHeadquarters: true,
    },
    {
        id: 'hyderabad',
        city: 'Hyderabad',  
        type: 'Regional Office',
        address: 'Hitech City, Madhapur, Hyderabad 500081',
        phone: '+91 40 0000 0000',
        email: 'hyderabad@opmw.in',
        isHeadquarters: false,
    },
    {
        id: 'bangalore',
        city: 'Bangalore',
        type: 'Regional Office',
        address: 'Whitefield, Bangalore 560066',
        phone: '+91 80 0000 0000',
        email: 'bangalore@opmw.in',
        isHeadquarters: false,
    },
    {
        id: 'noida',
        city: 'Noida',
        type: 'Regional Office',
        address: 'Sector 62, Noida 201309',
        phone: '+91 120 000 0000',
        email: 'noida@opmw.in',
        isHeadquarters: false,
    },
    {
        id: 'indore',
        city: 'Indore',
        type: 'Regional Office',
        address: 'Vijay Nagar, Indore 452010',
        phone: '+91 731 000 0000',
        email: 'indore@opmw.in',
        isHeadquarters: false,
    },
]

