export const PROJECTS = [
    {
        id: 'intl-voice',
        title: 'International Voice Campaign Deployment',
        category: 'BPO',
        summary: 'End-to-end setup of a 90-agent international voice campaign for a US-based client, including floor infrastructure, training, and KPI frameworks.',
        scope: 'Agent hiring, training program design, floor setup, dialer integration, quality monitoring, weekly reporting.',
        tech: ['Predictive Dialer', 'CRM Integration', 'QA Dashboard', 'VoIP'],
        outcome: 'Achieved 92% SLA compliance within 60 days. Campaign sustained at 90 agents across 2 shifts.',
        status: 'Completed',
    },
    {
        id: 'amazon-seller',
        title: 'Amazon Seller Support Program',
        category: 'BPO',
        summary: 'Dedicated backend support team for an Amazon seller managing catalog operations, case management, and inventory coordination.',
        scope: 'Catalog data entry, ASIN management, seller central case filing, inventory reconciliation, weekly KPI dashboards.',
        tech: ['Amazon Seller Central', 'Excel Automation', 'Internal Ticketing', 'Google Sheets'],
        outcome: 'Reduced catalog error rate by 40%. Case resolution time dropped from 5 days to 1.5 days.',
        status: 'Ongoing',
    },
    {
        id: 'non-voice',
        title: 'Multi-City Non-Voice Execution',
        category: 'BPO',
        summary: 'Scaled non-voice data operations across Chennai, Hyderabad, and Noida for a retail data aggregation client.',
        scope: 'Data extraction, categorization, quality checks, and daily delivery SLAs across 3 city teams.',
        tech: ['Internal QA Portal', 'Google Workspace', 'Excel', 'Python Scripts'],
        outcome: '120 executives deployed. 99.1% accuracy rate maintained across 3 months of delivery.',
        status: 'Completed',
    },
    {
        id: 'hrms-impl',
        title: 'Enterprise HRMS Implementation',
        category: 'HRMS',
        summary: 'Full deployment of OPMW HRMS for a 250-employee manufacturing client — covering payroll, attendance, leave, and compliance modules.',
        scope: 'Requirements gathering, data migration, payroll configuration, biometric integration, user training.',
        tech: ['OPMW HRMS', 'Laravel', 'MySQL', 'Biometric API', 'React'],
        outcome: 'Payroll processing time reduced from 3 days to 4 hours. 100% statutory compliance achieved.',
        status: 'Completed',
    },
    {
        id: 'brick-monitoring',
        title: 'Brick-Oriented Monitoring Web App',
        category: 'IT',
        summary: 'Real-time infrastructure monitoring platform built for a construction company tracking brick production across 8 sites.',
        scope: 'IoT data ingestion, real-time dashboard, alert system, multi-site admin panel, mobile-responsive UI.',
        tech: ['Laravel', 'React', 'MySQL', 'WebSockets', 'Chart.js', 'REST API'],
        outcome: 'Reduced production reporting lag from 24 hours to real-time. Admin panel adopted across all 8 sites.',
        status: 'Completed',
    },
    {
        id: 'workforce-automation',
        title: 'Workforce Automation Platform',
        category: 'IT',
        summary: 'Internal automation platform for OPMW operations — automating attendance imports, payroll triggers, leave approvals, and report generation.',
        scope: 'Workflow engine design, biometric data pipeline, automated payroll scheduler, email notification system.',
        tech: ['Laravel', 'MySQL', 'Cron Jobs', 'OPMW HRMS API', 'Vue.js', 'Redis'],
        outcome: 'Eliminated 40+ hours/month of manual HR operations. Fully live across all 5 OPMW branches.',
        status: 'Ongoing',
    },
]

export const PROJECT_FILTERS = ['All', 'BPO', 'IT', 'HRMS']
